# Generated by Django 3.2.21 on 2023-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(to='teacher_app.Subject'),
        ),
    ]
